swagger: "2.0"
info:
  description: This is the swagger file for simple task applicaiton example
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /tasks:
    get:
      operationId: services.dummy_data.get_todos
      tags:
        - Task
      summary: Lists all Tasks
      description: Read the list of tasks
      responses:
        200:
          description: Successful read task list operation
          schema:
            type: array
            items:
              properties:
                assignee:
                  type: string
                id:
                  type: integer
                status:
                  type: string
                task:
                  type: string
    post:
      operationId: services.dummy_data.add_todo
      tags:
        - Task
      summary: Create a task and add it to the tasks list
      description: Create a new task in the tasks list
      parameters:
        - name: task
          in: body
          description: task to create
          required: True
          schema:
            type: object
            properties:
              assignee:
                type: string
                description: Assignee of Task
              status:
                type: string
                description: Status of task
              task:
                type: string
                description: Description of task
      responses:
        201:
          description: Successfully created task in list
    put:
      operationId: services.dummy_data.edit_todo
      tags:
        - Task
      summary: Update a task in the tasks list
      description: Update a task in the tasks list
      parameters:
        - name: task
          in: body
          description: task to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: integer
              assignee:
                type: string
                description: Assignee of Task
              status:
                type: string
                description: Status of task
              task:
                type: string
                description: Description of task
      responses:
        200:
          description: Successfully updated task in list
  /task/{id}:
    delete:
      operationId: services.dummy_data.delete_todo
      tags:
        - Task
      summary: Delete a task in the task list
      description: Delete one task from the task list
      parameters:
        - name: id
          in: path
          description: Id of the task to delete from the task list
          type: integer
          required: True
      responses:
        200:
          description: Successfully delete task from task list